#!/usr/bin/env bash

echo "Running pre-commit hook..."

pnpm run format:check || exit 1

staged_files=$(git diff --cached --name-only --diff-filter=ACM)
if [ -z "$staged_files" ]; then
  exit 0
fi

PATTERN_BLOG='^content/blog/'
PATTERN_HOOKS='^.githooks/'

blog_changes=$(echo "$staged_files" | grep "$PATTERN_BLOG")
if [ -n "$blog_changes" ]; then
  pnpm run textlint || exit 1
fi

hooks_changes=$(echo "$staged_files" | grep "$PATTERN_HOOKS")
if [ -n "$hooks_changes" ]; then
  echo -e "\n> shellcheck .githooks/*"
  shellcheck .githooks/* || exit 1
fi

code_changes=$(echo "$staged_files" | grep -v "$PATTERN_BLOG" | grep -v "$PATTERN_HOOKS")
if [ -n "$code_changes" ]; then
  pnpm run typecheck || exit 1
  pnpm run check || exit 1
fi

echo ''
exit 0
