name: molt

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  udd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.x"

      - name: Update dependencies
        run: deno run -A jsr:@molt/cli $(find ./util/ -name "*.ts") --write

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update deno dependencies"
          title: "Update Deno dependencies"
          body: >
            Automated updates by [@molt/cli](https://github.com/hasundue/molt)
            and [create-pull-request](https://github.com/peter-evans/create-pull-request)
            GitHub action
          branch: update-deno-dependencies
          author: GitHub <noreply@github.com>
          delete-branch: true
