name: molt

on:
  schedule:
    - cron: "0 0 */3 * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  udd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: 2.7.12

      - name: Update dependencies
        run: deno run -A jsr:@molt/cli $(find ./scripts/ -name "*.ts") --write

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: "Update deno dependencies"
          title: "Update Deno dependencies"
          body: >
            Automated updates by [@molt/cli](https://github.com/hasundue/molt)
            and [create-pull-request](https://github.com/peter-evans/create-pull-request)
            GitHub action
          branch: update-deno-dependencies
          author: GitHub <noreply@github.com>
          delete-branch: true
