name: npm-update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  npm-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: run npm update
        run: npm update > ../output.txt

      - name: Read ../output.txt
        id: log
        uses: juliangruber/read-file-action@v1
        with:
          path: ../output.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "npm update"
          title: "npm update"
          body: |
            The output of `npm update` is

            ```
            ${{ steps.log.outputs.content }}
            ```
          branch: npm-update
          author: GitHub <noreply@github.com>
          delete-branch: true
